version: '3'

services:
  db:
    image: mysql
    container_name: pz-web-db
    restart: always
#    volumes:
#      - 'mysql_data_dir:/var/lib/mysql'
      #- './docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
    expose:
      - '3306'
      #ports:
      #- '3367:3306'
      #- '3329:3306'
    environment:
      MYSQL_DATABASE: 'acn'
      MYSQL_ROOT_PASSWORD: 'acn'
      MYSQL_USER: 'django'
      MYSQL_PASSWORD: 'django'
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    #command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0

  pz:
    build: .
    container_name: 'pz'
    image: afey/zomboid
    restart: unless-stopped
    depends_on:
      - 'db'
    links:
      - "db:database"
    env_file:
      - vars.env
#    environment:
#      SERVER_PORT: 16261
#      SERVER_PASSWORD: "temp"
#      SERVER_NAME: "anthesis-pzserver"
#      SERVER_PUBLIC_NAME: "Anthesis Gaming - Private Project Zomboid Server"
#      SERVER_PUBLIC_DESC: "The same old Project Zomboid, customised to our liking, deployed by yours truly"
#      PYTHONPATH: "/pz"
#      DJANGO_SETTIONGS_MODULE: "project_zomboid_manager.settings"
#      INSTDIR: "/pz/server-files/"
    command: tail -F /dev/null
    ports:
      - "8002:8000"
      - "27433:8766/udp"
      - "27434:8767/udp"
      - "16261:16261/udp"
      - "16262-16272:16262-16272"
      - "27431:27015"
    volumes:
      - /pz:/home/ubuntu/pz_server_manager
    stdin_open: true

    tty: true